apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-ubuntu-slave
  name: jenkins-ubuntu-slave-svc
  namespace: jenkins
spec:
  selector:
    app: jenkins-ubuntu-slave
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
