apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: nodeport-jnkns
  namespace: jenkins
spec:
  ports:
  - name: jenkins-nodeport
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30100
  selector:
    app: jenkins
  type: NodePort
status:
  loadBalancer: {}
