apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jnkns
  namespace: jenkins
spec:
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 1G
  hostPath:
    path: "/mnt/jenkins"
  storageClassName: hostpath

