apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jnkns
  namespace: jenkins
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: "1G" 
